const {test,expect}=require('@playwright/test')
test('Scenario1',async({page})=>{
await page.goto("https://www.lambdatest.com/selenium-playground/input-form-demo")
//await page.click("//button[text()='Submit']")
await expect(await page.locator("//button[text()='Submit']")).toHaveText('Please fill out this field')
await page.locator("//input[@id='name']").fill("Shashankreddy")
await page.locator("//input[@id='inputEmail4']").fill("shashankreddy.21321@gmail.com")
await page.locator("//input[@id='inputPassword4']").fill("Rssa@1997")
await page.locator("//input[@id='company']").fill("Info")
await page.locator("//input[@name='website']").fill("Info.com")
await page.locator("//select[@name='country']").selectOption('UnitedStates')
await page.locator("//input[@name='city']").fill("california")
await page.locator("//input[@name='address_line1']").fill("Ohri's street")
await page.locator("//input[@name='address_line2']").fill("PP")
await page.locator("//input[@placeholder='State']").fill("California")
await page.locator("//input[@name='zip']").fill("30017")
await page.click("//button[text()='Submit']")
const message=await expect(await page.locator("//p[@style='display: block;']")).toHaveText('Thanks for contacting us, we will get back to you shortly.')
await console.log(message)
page.waitForTimeout(5000)
})